# Generated by Django 5.2.7 on 2025-10-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='camis',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
