# Generated by Django 5.2.7 on 2025-10-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_restaurant_camis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-date']},
        ),
    ]
