# Generated by Django 5.2.7 on 2025-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='borough',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
