# Generated by Django 5.2.7 on 2025-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0004_restaurant_borough_restaurant_cuisine_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="violation_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
