# Generated by Django 5.2.7 on 2025-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0005_inspection_violation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="action",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="inspection",
            name="critical_flag",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
