# Generated by Django 5.2.7 on 2025-11-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspection_action_inspection_critical_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='forbidden_years',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='grading_explanations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='regraded_letter',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
