# Generated by Django 5.2.7 on 2025-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0007_restaurant_forbidden_years_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
